apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduled-audit-operator-manager
rules:
  - apiGroups: ["ops.kineticgain.com"]
    resources: ["scheduledaudits"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["ops.kineticgain.com"]
    resources: ["scheduledaudits/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
