//go:build !ignore_autogenerated

// Hand-written deepcopy (equivalent to controller-gen output) so the API types
// satisfy runtime.Object without a code-generation step in this repo.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ScheduledAudit) DeepCopyInto(out *ScheduledAudit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ScheduledAudit) DeepCopy() *ScheduledAudit {
	if in == nil {
		return nil
	}
	out := new(ScheduledAudit)
	in.DeepCopyInto(out)
	return out
}

func (in *ScheduledAudit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScheduledAuditList) DeepCopyInto(out *ScheduledAuditList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]ScheduledAudit, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *ScheduledAuditList) DeepCopy() *ScheduledAuditList {
	if in == nil {
		return nil
	}
	out := new(ScheduledAuditList)
	in.DeepCopyInto(out)
	return out
}

func (in *ScheduledAuditList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScheduledAuditSpec) DeepCopyInto(out *ScheduledAuditSpec) {
	*out = *in
	if in.Command != nil {
		out.Command = make([]string, len(in.Command))
		copy(out.Command, in.Command)
	}
	if in.Args != nil {
		out.Args = make([]string, len(in.Args))
		copy(out.Args, in.Args)
	}
}

func (in *ScheduledAuditSpec) DeepCopy() *ScheduledAuditSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduledAuditSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ScheduledAuditStatus) DeepCopyInto(out *ScheduledAuditStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		out.LastScheduleTime = in.LastScheduleTime.DeepCopy()
	}
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *ScheduledAuditStatus) DeepCopy() *ScheduledAuditStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduledAuditStatus)
	in.DeepCopyInto(out)
	return out
}
