apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-manager
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["ops.kineticgain.com"]
    resources: ["scheduledaudits"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["ops.kineticgain.com"]
    resources: ["scheduledaudits/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-manager
  labels:
    {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
